#ifndef SURVIVALSELECTIONMETHOD_H
#define SURVIVALSELECTIONMETHOD_H
enum class SurvivalSelectionMethod
{
    UNIFORM_RANDOM, TRUNCATION, FITNESS_PROPORTIONAL, TOURNAMENT_SELECTION_WITHOUT_REPLACEMENT
};
#endif
