DIVIDE 
SUBTRACT RAND 
RAND ADD 6 MULTIPLY 
DIVIDE ADD MULTIPLY DIVIDE MULTIPLY RAND 
ADJACENT_WALLS 3 NEAREST_ALLY NEAREST_ENEMY NEAREST_FRUIT NEAREST_PILL 3 NEAREST_ENEMY ADJACENT_WALLS 3 RAND NEAREST_ENEMY 
6 ADD 
NEAREST_ALLY ADD 
NEAREST_ALLY NEAREST_ENEMY 

